In [1]:
import numpy as np

# <span style='color:DodgerBlue'>Ex 1</span>
Printe os elementos dos seguintes dois vetores usando apenas um for:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

Depois, faça o mesmo usando numpy (usando a função nditer) e deixe um comentário sobre a diferença dos dois métodos.

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [19]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# com apenas um for conseguimos apenas mostrar os elementos completos dos primeiros vetores
for array in arr:
    print(array)
# com a função nditer conseguimos do mesmo modo imprimir cada elemento do vetor
for element in np.nditer(arr):
    print(element, end=' ')

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1 2 3 4 5 6 7 8 9 10 11 12 

# <span style='color:DodgerBlue'>Ex 2</span>
Peça para o usuário uma lista com as comidas favoritas dele, depois transforme isso em um objeto numpy. Agora transformado, elimine todas as comidas que começam com uma vogal. Mostre o resultado.

Exemplo:

Entrada: [maçã, uva, morango, melancia, acelga]

Saída: [maçã, morango, melancia]

In [72]:
fruits = input('Digite suas comidas favoritas:')
#fruits = 'maçã,uva,morango,melancia,acelga'
fruits = np.array([fruit for fruit in fruits.split(',')])
print(f'Entrada: {list(fruits)}')
voewls = ['a','e','i','o','u']
index = [fruit[0] in voewls for fruit in fruits]
print(f'Saída: {list(np.delete(fruits, index))}')

Entrada: ['maçã', 'uva', 'morango', 'melancia', 'acelga']
Saída: ['maçã', 'morango', 'melancia']


# <span style='color:DodgerBlue'>Ex 3</span>
Imprima a dimensão dos seguintes objetos numpy:

a = np.array(2)

b = np.array([1, 2, 3, 4, 5])

c = np.array([[1, 2, 3], [4, 5, 6]])

d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [78]:
a = np.array(2)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f'Array a: {a.ndim}')
print(f'Array b: {b.ndim}')
print(f'Array c: {c.ndim}')
print(f'Array d: {d.ndim}')

Array a: 0
Array b: 1
Array c: 2
Array d: 3


# <span style='color:DodgerBlue'>Ex 4</span>
Transforme o array em uma matriz 4 por 3 utilizando numpy.

arr = [1, 2, 3, 4, 'Amelia, 'Bruna, 'Carolina', 'Débora', True, False, False, True]

Depois, faça o mesmo para uma matriz 3 por 4.

In [90]:
array = [1, 2, 3, 4, 'Amelia', 'Bruna', 'Carolina', 'Débora', True, False, False, True]
np.reshape(array,(4,3))
np.reshape(array,(3,4))

array([['1', '2', '3', '4'],
       ['Amelia', 'Bruna', 'Carolina', 'Débora'],
       ['True', 'False', 'False', 'True']], dtype='<U11')

# <span style='color:DodgerBlue'>Ex 5</span>
Transforme o seguinte array em uma matriz 3D 3x3x3:

arr = range(27)

Deixe um comentário explicando o que significa uma matriz 3D.


In [95]:
arr = range(27)
np.reshape(arr,(3,3,3))
# matriz 3D possuí 3 coordenadas, ndim=3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

# <span style='color:DodgerBlue'>Ex 6</span>
Tente transformar o seguinte array em uma matriz 3x3x3

arr = [1, 2, 3, 4, 5, 6, 7, 8]

Funciona? Se sim, explique o motivo. Se não, explique o erro.

In [ ]:
arr = [1, 2, 3, 4, 5, 6, 7, 8]
np.reshape(arr,(3,3))
# não funciona pois o array precisa ter 9 elementos para formar uma matrix 3x3, seu atual tamanho é 8 

# <span style='color:DodgerBlue'>Ex 7</span>
Percorra o seguinte array utilizando for encaixado:

arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

Agora, percorra o mesmo array utilizando a função nditer de numpy.

In [104]:
array = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
for sub_array1 in array:
    for sub_array2 in sub_array1:
        for element in sub_array2:
            print(element, end=' ')
print()

array = np.array(array)
for element in np.nditer(array):
    print(element, end=' ')

1 2 3 4 5 6 7 8 
1 2 3 4 5 6 7 8 

# <span style='color:DodgerBlue'>Ex 8</span>
Percorra os indexes do seguinte array utilizando for encaixado:

arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

Agora faça o mesmo trabalho utilizando a função ndenumerate.

In [118]:
array = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
for index1, subarray1 in enumerate(array):
    for index2, subarray2 in enumerate(subarray1):
        for index3, subarray3 in enumerate(subarray2):
            print(f'index: ({index1},{index2},{index3})')

array = np.array(array)
for index in np.ndenumerate(array):
    print(index)

index: (0,0,0)
index: (0,0,1)
index: (0,1,0)
index: (0,1,1)
index: (1,0,0)
index: (1,0,1)
index: (1,1,0)
index: (1,1,1)
((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 1, 0), 3)
((0, 1, 1), 4)
((1, 0, 0), 5)
((1, 0, 1), 6)
((1, 1, 0), 7)
((1, 1, 1), 8)


# <span style='color:DodgerBlue'>Ex 9</span>
Junte os dois seguintes arrays na horizontal:

arr1 = [1, 2, 3]

arr2 = [4, 5, 6]

Depois, os junte verticalmente.

In [131]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.append(arr1,arr2))
print(np.reshape(np.append(arr1,arr2),(3,2),order='F'))

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


# <span style='color:Tomato'>DESAFIO 1</span> 
Utilizando manipulação de arrays, ache os indexes do array cujo valor possua apenas 2 vogais no nome usando numpy.

frutas = ['banana', 'morango, 'uva', 'pitaia', 'abacate', 'abacaxi', 'acerola', 'jenipapo', 'kiwi']

In [179]:
fruits = np.array(['banana', 'morango', 'uva', 'pitaia', 'abacate', 'abacaxi', 'acerola', 'jenipapo', 'kiwi'])

def count_vowel(char):
    vowels = ['a','e','i','o','u']
    result = ''
    for c in char:
        if c in vowels:
            result += c
    return len(result)

vowel_array = np.vectorize(count_vowel)(fruits)
np.where(vowel_array==2)

(array([2, 8], dtype=int64),)

# <span style='color:DodgerBlue'>Ex 11</span>
a) Tranforme o seguinte array 2D em dois arrays 2D:

arr = [[1, 2], [3, 4], [5, 6], [7, 8]]

b) Transforme o seguinte array em três arrays com apenas uma coluna:

arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [235]:
# a
arr = [[1, 2], [3, 4], [5, 6], [7, 8]]
#np.concatenate((np.array(arr[:2]),np.array(arr[2:])))
np.array([np.array(arr[:2]),np.array(arr[2:])])
# b
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.reshape(arr,[-1,1,3])

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

# <span style='color:Tomato'>DESAFIO</span> 
Utilizando manipulação de arrays, vamos seguir um conjunto de passos para organizar alguns dados. Teremos nesse seguinte array uma ordem que segue:

[Nome do aluno, idade, 'gênero', signo, altura, nota do 1° semestre, nota do 2° bimestre, se está ou não inscrito no próximo ano da escola, nome do outro aluno, idade do outro aluno...]

arr = ['Amélia', 13, 'F', 'peixes', 1.51, 9, 7, True, 'Bruno', 14, 'O', 'leão', 1.60, 4, 10, False, 'João', 14, 'M', 'escorpião', 1.58, 8, 9, True, 'Jordana', 13, 'F', 'escorpião', 1.72, 9, 9, False]

a) Enumere os indexes de todas as informações que são do tipo string.

b) Separe essas informações do objeto arr de forma que cada aluno tenha seu próprio array.

c) Separe em duas colunas, a primeira com o nome, a idade, o gênero e o signo e a segunda com a altura, nota do primeiro bimestre, nota do segundo bimestre e se está ou não inscrito no próximo ano.

d) Elimine o gênero de todos os arrays cujos alunos tem menos de 14 anos.

In [323]:
arr = ['Amélia', 13, 'F', 'peixes', 1.51, 9, 7, True, 'Bruno', 14, 'O', 'leão', 1.60, 4, 10, False, 'João', 14, 'M', 'escorpião', 1.58, 8, 9, True, 'Jordana', 13, 'F', 'escorpião', 1.72, 9, 9, False]

array = [index for index, element in enumerate(arr) if isinstance(element,str)]
print(f'A) {array}')

array = [arr[index:index+8] for index in range(0,len(arr),8)]
print(f'B) {array}')

array = np.reshape(np.array(array),(4,2,4))
print(f'C) {array}')

for index,value in enumerate(array):
    if int(value[0][1])<14:
        np.put(array, [index*8+2],[None])
print(f'D) {array}')

A) [0, 2, 3, 8, 10, 11, 16, 18, 19, 24, 26, 27]
B) [['Amélia', 13, 'F', 'peixes', 1.51, 9, 7, True], ['Bruno', 14, 'O', 'leão', 1.6, 4, 10, False], ['João', 14, 'M', 'escorpião', 1.58, 8, 9, True], ['Jordana', 13, 'F', 'escorpião', 1.72, 9, 9, False]]
C) [[['Amélia' '13' 'F' 'peixes']
  ['1.51' '9' '7' 'True']]

 [['Bruno' '14' 'O' 'leão']
  ['1.6' '4' '10' 'False']]

 [['João' '14' 'M' 'escorpião']
  ['1.58' '8' '9' 'True']]

 [['Jordana' '13' 'F' 'escorpião']
  ['1.72' '9' '9' 'False']]]
D) [[['Amélia' '13' 'None' 'peixes']
  ['1.51' '9' '7' 'True']]

 [['Bruno' '14' 'O' 'leão']
  ['1.6' '4' '10' 'False']]

 [['João' '14' 'M' 'escorpião']
  ['1.58' '8' '9' 'True']]

 [['Jordana' '13' 'None' 'escorpião']
  ['1.72' '9' '9' 'False']]]
