In [1]:
import numpy as np

## Questão 1 - Crie um numpy array com 10 elementos 0, exceto o elemento de índice 6, que deve ser 20

In [6]:
array = np.array([0]*5+[6]+[0]*3)

array

array([0, 0, 0, 0, 0, 0, 6, 0, 0, 0])

## Questão 2 - Crie uma função que receba um numpy array e retorne um array de 20 elementos contendo apenas o maior elemento do array recebido

In [23]:
def maxValue(array):
    maximum = max(array)
    auxList = []
    for index in range(20):
        auxList.append(maximum)
    return np.array(auxList)

array = np.array([0,1,2,3,4,5])

print(maxValue(array))


[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]


## Questão 3 - Faça uma função que receba um array, eleve ele ao quadrado, some 3, pegue apenas o elementos que são diferentes de 4 e, por último, divida por 4. Depois, retorne esse array modificado

In [48]:
def messyArray(array):
    array **= 2
    print(array)
    array += 3
    print(array)
    array = array[array!=4]
    array = array/4
    print(array)
    #array /= 4
    
    return array

array = np.array([5,4,2,3,4,5])

print(messyArray(array).shape)
print(messyArray(array))
    

[25 16  4  9 16 25]
[28 19  7 12 19 28]
[7.   4.75 1.75 3.   4.75 7.  ]
(6,)
[784 361  49 144 361 784]
[787 364  52 147 364 787]
[196.75  91.    13.    36.75  91.   196.75]
[196.75  91.    13.    36.75  91.   196.75]


## Questão 4 - Faça uma função que receba dois array, junte os dois e retorne

In [42]:
def joinArrays(array1, array2):
    return array1 + array2

array1 = [2,3,1,2]
array2 = [0,1,4,0]

print(joinArrays(array1,array2))
    

[2, 3, 1, 2, 0, 1, 4, 0]


## Questão 5 - Faça uma função que descreva meu array exibindo os seguintes dados com até 3 casas decimais: máx, min, média, desvio padrão (standard deviation). A exibição deve ser da seguinte forma:

```
******************************
Array: array([0, 5, 6, 8, 9])

Max: 9
Min: 0
Media: 5.6
Desvio padrao: 3.137
******************************
```

In [ ]:
def describeArray(array):
    print('******************************')
    print(f'Array: {array}\n')
    print(f'Max: {max(array)}')
    print(f'Min: {min(array)}')
    print(f'Media: {mean(array)}')
    print(f'Descio padrao: {std}')
    print('******************************')